### PR TITLE
updated rasterPointCount function and help file

### PR DESCRIPTION
**Pull request by fshearer**

### CODE REVIEW

**Comment by goldingn** [comment]
This builds and passes checks just fine on my mac.

However I get NAs in the results if I run the example:

```r
> example("rasterPointCount")

...

> head(count_data)
  Freq      x      y
1   NA 178420 333980
2   NA 178460 333980
3   NA 178500 333980
4   NA 178540 333980
5   NA 178580 333980
6   NA 178620 333980
> tail(count_data)
     Freq      x      y
9195    0 179020 330980
9196    0 179020 330500
9197    0 180020 330980
9198    1 181020 332980
9199    2 180020 331980
9200    1 179020 329980
```

Not sure what's causing this.

It might also be a bit clearer if you added a couple of different use cases in the example - i.e. run it four times, toggling the extract and absence arguments. That way it will make sure all of those run without throwing errors, and we can compare the results.

Could you address these things before I merge the PR?

The readability and error checking in the code is really impressive by the way!

**Comment by fshearer** [comment]
Should be all good now.....

**Comment by goldingn** [comment]
That's great. I'm accepting this PR.

Only thing is this note from `R CMD check --as-cran`:
`
Rd file 'rasterPointCount.Rd':
  \examples lines wider than 100 characters:
     # get count of point for each raster pixel for occurrence and pseudo-absence data and extract raster values
`
It would be nice to break this onto two lines for the sake of tidiness. I'll make this change in a sec, so remember to sync your local repo and GH fork before you start editing the package next time!

**Comment by fshearer** [comment]
Ok cool. Does it get a squirrel?

**Comment by goldingn** [comment]
:shipit:

**Pull request merged**
